basePath: /
definitions:
  dto.WalletTransferRequest:
    properties:
      amount:
        type: number
      externalFromWalletId:
        type: string
      externalToWalletId:
        type: string
    type: object
  dto.WalletUpdateRequest:
    properties:
      amount:
        type: number
      content:
        type: string
      externalWalletId:
        type: string
      updateType:
        type: string
      walletType:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample finance service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Finance Service API
  version: "1.0"
paths:
  /wallets/convert_balance:
    post:
      consumes:
      - application/json
      description: Transfer balance from one wallet to another
      parameters:
      - description: Convert Request
        in: body
        name: convertRequest
        required: true
        schema:
          $ref: '#/definitions/dto.WalletTransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Convert wallet balance
      tags:
      - wallets
  /wallets/update_balance:
    post:
      consumes:
      - application/json
      description: Top up the balance of a wallet
      parameters:
      - description: Topup Request
        in: body
        name: topupRequest
        required: true
        schema:
          $ref: '#/definitions/dto.WalletUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Top up wallet balance
      tags:
      - wallets
swagger: "2.0"
